name: Fetch Free Game Deals

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tweet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: dawidd6/action-download-artifact@v6
        with:
          name: last_checked
          path: last_checked.txt
          search_artifacts: true
      # Runs a single command using the runners shell
      - name: Fetch
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          OSNN_DISCORD_WEBHOOK: ${{ secrets.OSNN_DISCORD_WEBHOOK }}
          VISA_DISCORD_WEBHOOK: ${{ secrets.VISA_DISCORD_WEBHOOK }}
        run: python index.py
      - uses: actions/upload-artifact@v4
        with:
          name: last_checked
          path: last_checked.txt
        